### ISSUE TITLE
Not integrate well with asyncrun.vim

### ISSUE THREAD

**Issue by glyh** [folke/trouble.nvim#146]
[![asciicast](https://asciinema.org/a/x60akuzTjSshfa7XyhWPeEURn.svg)](https://asciinema.org/a/x60akuzTjSshfa7XyhWPeEURn)

**Comment by folke** [comment]
That's because the file entry in the quickfix list is empty

**Comment by glyh** [comment]
Well, I think that's not the key point. 

[![asciicast](https://asciinema.org/a/X0bYYEJ4aC2pgWuh0lvg60d4K.svg)](https://asciinema.org/a/X0bYYEJ4aC2pgWuh0lvg60d4K)

**Comment by folke** [comment]
Should be fixed now. Let me know if you have any more issues

**Comment by glyh** [comment]
This works and don't yield errors, but I still can't see the quickfix messages. Is this because the other side(asyncrun.vim) is doing some dirty hacks?
