### ISSUE TITLE
No Results Appear Available

### ISSUE THREAD

**Issue by atomdmac** [folke/trouble.nvim#91]
# Description

No results appear when opening the `:Trouble` window.  This includes all modes except `loclist` but only after a `loclist` has been generated using `:LspDocumentDiagnostics` (which I believe comes from `vim-lsp`).

I'm guessing that I'm missing some pivotal config step but I haven't been able to figure out what I'm leaving out.

Any help would be appreciated.

# Setup

OS: `MacOS Mojave 10.14.6`
Terminal: `iTerm 3.4.8`
NVIM: `0.5.0` + Nightly build
LSP Client: `vim-lsp`
LSP Servers Tested:
* `vim-language-server`
* `eslint-language-server`
* `typescript-language-server`

# Init.vim

```viml
call plug#begin()
Plug 'kyazdani42/nvim-web-devicons'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'folke/trouble.nvim'
call plug#end()

let g:lsp_diagnostics_enabled = 1

lua << EOF
  require("trouble").setup {
    -- Empty
  }
EOF
```

**Comment by HungryJoe** [comment]
I've encountered a bug where `:Trouble lsp_references` turns up an empty results window even though `:lua vim.lsp.buf.references()` shows a list of references like normal.

## Environment
### Neovim version
NVIM v0.6.0-dev+1745-g516775e9d

### LSP client
Built-in Neovim LSP client

### Operating system/version
macOS Catalina 10.15.7

### Terminal
iTerm2

### $TERM variable
xterm-256color

### Init.vim
let g:python3_host_prog='~/.asdf/installs/python/3.9.2/bin/python'
let g:python_host_prog='/usr/bin/python2.7'
lua << EOF
    require('packer').startup(function()
        use 'neovim/nvim-lspconfig'
        use {
            "folke/trouble.nvim",
            requires = "kyazdani42/nvim-web-devicons",
        }
    end)
EOF
lua << EOF
    local lsp = require('lspconfig');
    lsp.pyright.setup{}
EOF
lua << EOF
    require'trouble'.setup{}
EOF

## Steps to reproduce
1. Open a Python file
2. Move to a variable that is referenced multiple times in the workspace
2. Enter `:Trouble lsp_references`

## Expected behavior
The results of `:lua vim.lsp.buf.references()` should show up in a new Trouble window.

## Actual behavior
An empty Trouble window shows up, with the message `[Trouble] no results`.

**Comment by HungryJoe** [comment]
Apologies, I believe my bug was introduced upstream quite recently in [this PR](https://github.com/neovim/neovim/pull/15504). I've fixed it in [my fork](https://github.com/HungryJoe/trouble.nvim) for others using the nightly build of Neovim, and I'll make a PR if/when this change make it into a stable build.

**Comment by atomdmac** [comment]
Thanks @HungryJoe !  I gave your fork a try but it looks like maybe the issue I'm seeing has a different cause (as it's still occurring for me).

**Comment by atomdmac** [comment]
I'm not sure if this is related but I did see this in the output from `nvim -V9nvim.log`:

```
not found in 'packpath': "pack/*/start/*/indent.vim"
not found in 'packpath': "start/*/indent.vim"
not found in 'runtimepath': "lua/trouble.lua"
not found in 'packpath': "pack/*/start/*/lua/trouble.lua"
not found in 'packpath': "start/*/lua/trouble.lua"
not found in 'runtimepath': "lua/trouble/providers.lua"
not found in 'packpath': "pack/*/start/*/lua/trouble/providers.lua"
not found in 'packpath': "start/*/lua/trouble/providers.lua"
```

None of these files exist under the `~/.config/nvim/plugged/trouble.nvim/` directory (though, there are `./lua/trouble` and `./lua/trouble/providers` directories).  

Other than that, I don't see any other errors.

**Comment by atomdmac** [comment]
So this appears to be caused by the fact that I was using `vim-lsp` as my LSP client instead of NVIM's built-in LSP support.  Converting my setup to use `nvim-lspconfig` et al fixed this.
